### ISSUE TITLE
recenter causes img2img processes (which include adetailer) to result in blue-tinted images.

### ISSUE THREAD

**Issue by zcatharisis** [Haoming02/sd-webui-diffusion-cg#1]
As title says, any process involving img2img and recenter results in a cooler tint to the image, noticeable even with 0.2 strength. 

Admittedly, it's not really a problem in regular img2img since it can simply be turned off, but it's a problem when using adetailer, an automatic img2img inpaint extension. (https://github.com/Bing-su/adetailer/)

Really hoping you can fix this, it helps reduce that 'ai' feel to images.

**Comment by Haoming02** [comment]
So, you mean it specifically causes blue tint when `adetailer` is also enabled?

**Comment by Haoming02** [comment]
I've managed to recreate a similar problem now. While not a blue tint, the reactangular area processed by `adetailer` often comes out brighter than the rest during **img2img**.
Currently, I came up with a temporary solution, but it would break other functions. So I'm still trying to fix it.

**Comment by Haoming02** [comment]
Please test if the issue still persists~

**Comment by zcatharisis** [comment]
Completely fixed, thanks a lot!
