### ISSUE TITLE
Setting default values doesn't seem to work

### ISSUE THREAD

**Issue by zcatharisis** [Haoming02/sd-webui-diffusion-cg#2]
Actions: 
1.Enable the extension and set Recenter and Normalization parameters in txt2img and img2img. 
2. Go to Settings>Defaults. Click 'view settings' to confirm that defaults are being changed. Click Apply and Apply Settings to make sure the changes are set.

Expected Behavior:
On running a new instance of Webui, the extension should be enabled and parameters should be automatically set according to the default used in step 1 above.

Actual Behavior:
On running a new instance of Webui, the extension is disabled and parameters are reset to 0 and Disabled.

My ui-config.json isn't set to read-only and any changes to other WebUi settings that I input to be default are reflected in the new instance. It's only changes to this extension that doesn't stick.
Please let me know if this is an issue on my end only. It's not really a big problem, just a minor annoyance when I run my first few images and realize that I forgot to turn this on again. 

Thanks for the extension and for your work again

**Comment by Haoming02** [comment]
Oh, about that...
Since the Extension was still experimental, I added a script to always clear out the cached slider values, lest that I change the ranges in the future, thus breaking the effects in the process.

In the meantime, you can simply comment out this specific line:
[script_callbacks.on_before_ui(refresh_sliders)](https://github.com/Haoming02/sd-webui-diffusion-cg/blob/main/scripts/cg_version.py#L19)

*(Just add a `#` at the begining of the line)*

**Comment by Haoming02** [comment]
Though, I was indeed thinking about adding an option in the settings to always enable the effects automatically~

**Comment by zcatharisis** [comment]
Thanks! Glad to know it wasn't an error on my end at least.

If you want ideas on a toggle to enable or disable the extension on startup, negpip (https://github.com/hako-mikan/sd-webui-negpip) has a similar button.
![image](https://github.com/Haoming02/sd-webui-diffusion-cg/assets/143588182/8700f2f0-da2c-4e36-9b7f-ce7ad4d1e4cb)

**Comment by Haoming02** [comment]
You can now make either effect default to enabled by going to the `Diffusion CG` section of **Settings** tab~
