### ISSUE TITLE
used to work in SDNEXT...

### ISSUE THREAD

**Issue by RGX650** [Haoming02/sd-webui-diffusion-cg#3]
recently, ui is off on grey boxes (if i am not mistaken)...
also i have now - 'p' is not defined error - regarding ksampler vs tensor_debug.py + cgdiffusion.py
![Capture d'écran 2023-12-03 235136](https://github.com/Haoming02/sd-webui-diffusion-cg/assets/139933536/a87e696d-dc55-4bfe-925c-feb540a1307f)

**Comment by Haoming02** [comment]
Not planning to support for SD.Next

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
Plan for it then.
