### ISSUE TITLE
Seems to have no effect on A1111 1.8.0

### ISSUE THREAD

**Issue by zcatharisis** [Haoming02/sd-webui-diffusion-cg#4]
Hello, it's me again. The extension doesn't seem to work on 1.8.0 where it worked fine in 1.7.0. The console isn't spitting out any errors, it's working as if the extension doesn't exist.

Tested by generating it enabling and disabling through the txt2img checkbox and through Diffusion CG settings ('always perform on')
Also tested by enabling extension and turning one of the color options to -1. No effect unfortunately. 

Tried to resolve the issue by reinstalling the extension, but it didn't work.

**Comment by Haoming02** [comment]
Seems fine to me~

```ruby
(high quality, best quality), 1girl, solo, smile, blush
Negative prompt: (low quality, worst quality:1.2), EasyNegative, EasyNegativeV2
Steps: 24, Sampler: Euler a, CFG scale: 7.5, Seed: 8756, Size: 512x512, Model hash: ad0293e906, Model: UHD-23-pruned, Clip skip: 2, Token merging ratio: 0.1, RNG: CPU, NGMS: 2, ReCenter Str: 1, Normalization: True, SD_ver: 1.5, Version: v1.8.0
```
<p align="center">
<img src="https://github.com/Haoming02/sd-webui-diffusion-cg/assets/73768377/fe6429cc-a806-4a65-b2e2-14f32033984a" width=256>
<img src="https://github.com/Haoming02/sd-webui-diffusion-cg/assets/73768377/b2ffb18f-7da3-48c9-b4d5-0521b3edb66e" width=256>
<br>
<code>On</code> | <code>Off</code>
</p>

**Comment by zcatharisis** [comment]
Thanks, ~~I'll have to check what's wrong with my own build and report back in case it helps.~~
Nevermind, the issue fixed itself. I didn't even change anything from when I last opened A1111
